### ISSUE TITLE
Adjusted inside of heredoc when the line starts with #

### ISSUE THREAD

**Issue by thinca** [rbtnn/vim-vimscript_formatter#4]
Consider the below Vim script:

```vim
let ruby =<< RUBY
  require('csv')
RUBY

let c =<< C
  #include <stdio.h>
C
```

When re-indent the all lines, the line `#include` is adjusted.

```vim
let ruby =<< RUBY
  require('csv')
RUBY

let c =<< C
#include <stdio.h>
C
```

I expect there are no changes.

**Comment by rbtnn** [comment]
Typing `:echo synIDattr(synID(line('.'), 1, 1), 'name')`  at `#include <stdio.h>` line: 
![image](https://user-images.githubusercontent.com/1595779/133620907-db80e3e2-ca47-4662-b36a-dd9ac34d950f.png)

It seems this bug is occurred due to not support Vim9 syntax yet.

**Comment by rbtnn** [comment]
https://github.com/vim/vim/blob/master/runtime/syntax/vim.vim#L400
I do not know why this line contains `vimComment,vim9Comment`.

**Comment by rbtnn** [comment]
https://github.com/vim/vim/commit/113cb513f76d8866cbb6dc85fa18aded753e01da
Fixed.
